# Generated by Django 2.2.28 on 2025-12-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('tags', models.CharField(blank=True, help_text='使用英文逗号分隔多个标签，如：Python,Django', max_length=200, verbose_name='标签')),
                ('is_publish', models.BooleanField(default=True, verbose_name='是否发布')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
                'ordering': ['-create_date'],
            },
        ),
    ]
